# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  azureContainerRegistry: lukasia3.azurecr.io
  azureSubscriptionEndpoint: container
  pulumiProject : 'pulum.csproj'
  pulumiStack : 'stack'

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
steps:

- task: DockerCompose@0
  inputs:
    displayName: Build 
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(azureSubscriptionEndpoint)
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--build --no-start'

- task: DockerCompose@0
  displayName: Check - Images
  inputs:
    dockerComposeCommand: ps
- task: DockerCompose@0
  displayName: Push services
  inputs:
    action: Push services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: kong2
    qualifyImageNames: true

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: $(pulumiProject)
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: $(pulumiProject)
    arguments: '--nologo -c Release'


