# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: registry-sc
    tags: lukasia
    
- task: DockerCompose@0
  displayName: Container registry login
  inputs:
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: container
    azureContainerRegistry: registry-sc
    dockerComposeFile: docker-compose.yml
    dockerComposeCommand: up --build --no-start
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      registry-sc
    repository: "lukas-test"
    command: push
    tags: lukasia

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
