version: '2.1'
networks:
  kong-net:
  
services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
#    environment:
#      KONG_DATABASE: "off"
#      KONG_DECLARATIVE_CONFIG: "kong.yml"
#      KONG_PROXY_ACCESS_LOG: kong
    image: lukasia3.azurecr.io/kong2
    container_name: kong
    build: .

    networks:
      - kong-net
    ports:
    - "8000:8000"
    - "8001:8001"
    - "8002:8002"

    volumes:
      - ./config:/kong
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
      