version: '2.1'
networks:
  kong-net:
  
services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: lukasia3.azurecr.io/kong
    container_name: kong
    build: .
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "kong.yml"
      KONG_PROXY_ACCESS_LOG: kong

    networks:
      - kong-net
    ports:
    - "8000:8000"
    - "8001:8001"
    - "8002:8002"
    #- "8443:8443"
    #- "8444:8444"
    #- "8002:8002"
    #- "8445:8445"
    #- "8003:8003"
    #- "8004:8004"
    volumes:
      - ./config:/kong
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
      
  #######################################
  # Example Microservice
  #######################################
  #app:
  #  build: .
  #  container_name: kong-app
  #  networks:
  #    - kong-net
  #  restart: on-failure